.Dd April 16, 2016
.Dt LSD 1
.Os disputils
.Sh NAME
.Nm lsd
.Nd list connected displays
.Sh SYNOPSIS
.Nm
.Op Fl a
.Sh DESCRIPTION
.Nm
lists connected displays.
.Pp
By default,
.Nm
lists only displays that are in use.
.Bl -tag -width Ds
.It Fl a
List all connected displays, not only those who are in use.
.El
.Sh ENVIRONMENT
.Nm
acts on the X display specified by the
.Ev DISPLAY
variable
.Sh SEE ALSO
.Xr dattr 1
